//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ControlBrushVeryDark {
            get {
                return ((global::System.Drawing.Color)(this["ControlBrushVeryDark"]));
            }
            set {
                this["ControlBrushVeryDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 32, 32")]
        public global::System.Drawing.Color ControlBrushDark {
            get {
                return ((global::System.Drawing.Color)(this["ControlBrushDark"]));
            }
            set {
                this["ControlBrushDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ControlBrush {
            get {
                return ((global::System.Drawing.Color)(this["ControlBrush"]));
            }
            set {
                this["ControlBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96, 96, 96")]
        public global::System.Drawing.Color ControlBrushLight {
            get {
                return ((global::System.Drawing.Color)(this["ControlBrushLight"]));
            }
            set {
                this["ControlBrushLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ControlBrushVeryLight {
            get {
                return ((global::System.Drawing.Color)(this["ControlBrushVeryLight"]));
            }
            set {
                this["ControlBrushVeryLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144, 144, 144")]
        public global::System.Drawing.Color TextBrushDark {
            get {
                return ((global::System.Drawing.Color)(this["TextBrushDark"]));
            }
            set {
                this["TextBrushDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("176, 176, 176")]
        public global::System.Drawing.Color TextBrush {
            get {
                return ((global::System.Drawing.Color)(this["TextBrush"]));
            }
            set {
                this["TextBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("208, 208, 208")]
        public global::System.Drawing.Color TextBrushLight {
            get {
                return ((global::System.Drawing.Color)(this["TextBrushLight"]));
            }
            set {
                this["TextBrushLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color TextBrushVeryLight {
            get {
                return ((global::System.Drawing.Color)(this["TextBrushVeryLight"]));
            }
            set {
                this["TextBrushVeryLight"] = value;
            }
        }
    }
}
